---
- name: Deploy VPN services configs for SP L3VPN lab
  hosts: r3:r5
  gather_facts: false
  connection: local

  vars:
    junos_user: jcluser

  vars_prompt:
    - name: DEVICE_PASSWORD
      prompt: "Device password"
      private: yes

  tasks:
    - name: Push VPN services config with set
      juniper.device.config:
        host: "{{ ansible_host }}"
        user: "{{ junos_user }}"
        passwd: "{{ DEVICE_PASSWORD }}"
        port: "{{ ansible_port }}"
        ssh_config: "/tmp/blank_ssh_config"
        src: "{{ playbook_dir }}/../rendered/isis_multi_area/vpn/lab-{{ inventory_hostname }}.set"
        load: set
        comment: "Deploy SP L3VPN VPN services"