---
- import_playbook: deploy_sp_l3vpn_on_isis_multi_area__ce.yml
- import_playbook: deploy_sp_l3vpn_on_isis_multi_area__base.yml
- import_playbook: deploy_sp_l3vpn_on_isis_multi_area__bgp.yml
- import_playbook: deploy_sp_l3vpn_on_isis_multi_area__vpn.yml