---
- name: Load rendered base configs
  hosts: junos
  gather_facts: false
  connection: local

  vars:
    junos_user: jcluser
    junos_passwd: "Juniper!1"

  tasks:
    - name: Push rendered base config
      juniper.device.config:
        host: "{{ ansible_host }}"
        user: "{{ junos_user }}"
        passwd: "{{ junos_passwd }}"
        port: "{{ ansible_port }}"
        load: merge
        src: "../rendered/{{ inventory_hostname }}-base.conf"
        comment: "Rendered base config"