---
- name: Load full configs onto Junos routers
  hosts: junos
  gather_facts: false
  connection: local

  vars:
    junos_user: jcluser
    junos_passwd: "Juniper!1"

  tasks:
    - name: Load override and commit from local file
      juniper.device.config:
        host: "{{ ansible_host }}"
        user: "{{ junos_user }}"
        passwd: "{{ junos_passwd }}"
        port: "{{ ansible_port }}"
        load: "override"
        src: "{{ cfg_file }}"
        comment: "Loaded by Ansible"
      register: response

    - name: Show result
      ansible.builtin.debug:
        var: response
