---
- name: Load rendered configs to Junos routers with merge
  hosts: junos
  gather_facts: false
  connection: local

  vars:
    junos_user: jcluser
    junos_passwd: "Juniper!1"

  tasks:
    - name: Push rendered config with merge
      juniper.device.config:
        host: "{{ ansible_host }}"
        user: "{{ junos_user }}"
        passwd: "{{ junos_passwd }}"
        port: "{{ ansible_port }}"
        src: "{{ cfg_file }}"
        load: merge
        comment: "Load rendered config (merge)"