---
- name: Load rendered base configs
  hosts: junos
  gather_facts: false
  connection: local

  vars:
    junos_user: jcluser

  vars_prompt:
    - name: DEVICE_PASSWORD
      prompt: "Device password"
      private: yes

  tasks:
    - name: Push rendered base config
      juniper.device.config:
        host: "{{ ansible_host }}"
        user: "{{ junos_user }}"
        passwd: "{{ DEVICE_PASSWORD }}"
        port: "{{ ansible_port }}"
        load: merge
        src: "../rendered/ospf_multi_area/base/{{ inventory_hostname }}-base.conf"
        comment: "Rendered base config"