---
- name: Router ping test
  hosts: junos
  gather_facts: false
  connection: local

  vars:
    junos_user: jcluser

  vars_prompt:
    - name: DEVICE_PASSWORD
      prompt: "Device password"
      private: yes

  tasks:
    - name: Ping 10.100.100.2 from router
      juniper.device.ping:
        host: "{{ ansible_host }}"
        user: "{{ junos_user }}"
        passwd: "{{ DEVICE_PASSWORD }}"
        port: "{{ ansible_port }}"
        dest: 10.100.100.2 
      register: result

    - name: Show result
      debug:
        var: result
