---
- name: Test Junos connectivity
  hosts: junos
  gather_facts: false
  connection: local

  vars:
    junos_user: jcluser
  
  vars_prompt:
    - name: DEVICE_PASSWORD
      prompt: "Device password"
      private: yes

  tasks:
    - name: Run show version
      juniper.device.command:
        host: "{{ ansible_host }}"
        user: "{{ junos_user }}"
        passwd: "{{ DEVICE_PASSWORD }}"
        port: "{{ ansible_port }}"
        commands:
          - "show version"
      register: out

    - name: Print output
      ansible.builtin.debug:
        var: out.stdout_lines
